### ISSUE TITLE
Problems using uart module...

### ISSUE THREAD

**Issue by stacksmith** [cyrozap/iCEstick-UART-Demo#2]
1) Cloning your repo leaves the directory /cores/osdvu empty...
2) Manually git-cloned the uart repo.  Synthesis errors:

```
2.2.2. Analyzing design hierarchy..
Top module:  \top
Used module:     \uart

2.2.3. Executing AST frontend in derive mode using pre-parsed AST for module `\uart'.
ERROR: Requested parameter `\sys_clk_freq' does not exist in module `\uart'!
make: *** [uart_demo.blif] Error 1
```

My guess is that you've parametrized the uart module to recalculate to different clocks?  Could you update your repo to include all the code needed to build the project?

Thanks

**Comment by cyrozap** [comment]
Please delete whatever you cloned, then follow these steps exactly: https://github.com/cyrozap/iCEstick-UART-Demo#building

**Comment by stacksmith** [comment]
Thank you, I will try that.  I suppose RTFM applies, apologies.
